version: '3.5'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - fpm
    volumes:
      - ./html:/var/www/htdocs/
      - ./conf.d:/etc/nginx/conf.d:cached

  fpm:
    image: php:7-fpm-alpine
    volumes:
      - ./html:/var/www/htdocs/
